apiVersion: apps/v1
kind: Deployment
metadata:
  name: ContosoWS
  labels:
    app: ContosoWS
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1723159980629
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ContosoWS
  template:
    metadata:
      labels:
        app: ContosoWS
    spec:
      containers:
        - name: ContosoWS
          image: acrworkflow1723159980629.azurecr.io/image-workflow-1723159980629:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
