apiVersion: v1
kind: Service
metadata:
  name: ContosoWS
  namespace: namespace-workflow-1723159980629
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: ContosoWS
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000