apiVersion: v1
kind: Service
metadata:
  name: ContosoWF1
  namespace: namespace-workflow-1723157608918
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: ContosoWF1
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000